name: Deploy HTML Site

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            git config --global --add safe.directory /var/www/html
            cd /var/www/html
            git pull origin main

            echo "Deployment completed successfully"
